=== lgvalent/monstrengo/MonstrengoMetadata/entityMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://orionsoft.net.br/entityMetadata" xmlns:local="http://orionsoft.net.br/entityMetadata"
	elementFormDefault="qualified">
	<!-- Define um conjunto comum de metadados de textos aplicáveis a Entity, 
		Group e Property -->
	<xsd:attributeGroup name="commonMetadataAttributes">
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="label" type="xsd:string" default=""/>
		<xsd:attribute name="hint" type="xsd:string" default=""/>
		<xsd:attribute name="description" type="xsd:string" default=""/>
		<xsd:attribute name="colorName" type="local:colorNameType">
			<xsd:annotation><xsd:documentation> 
			Permite definir a cor pelo nome CSS ou pelo valor
			hexadecimal correspondente.
			</xsd:documentation></xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>

	<!-- Define o tipo que valida o nome de uma classe -->
	<xsd:simpleType name="classNameType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(([a-z]|[0-9])+.)*[A-Z][a-z]*([A-Z]|[a-z]|[0-9_])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Permite definir a cor pelo nome ou pelo código Hexadecimal -->
	<xsd:simpleType name="colorNameType">
		<xsd:union>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:annotation>
						<xsd:documentation>
							Fontes:http://www.kylirhorton.com/2008/a-regular-expression-that-matches-css-colors/
						</xsd:documentation>
					</xsd:annotation>
					<xsd:pattern
						value="(#[0-9a-fA-F]{3,6})|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" />
					<!-- xsd:pattern value="#([0-9A-Fa-f]{3,6})\b)|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" 
						/> -->
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="aqua" />
					<xsd:enumeration value="black" />
					<xsd:enumeration value="blue" />
					<xsd:enumeration value="fuchsia" />
					<xsd:enumeration value="gray" />
					<xsd:enumeration value="green" />
					<xsd:enumeration value="lime" />
					<xsd:enumeration value="maroon" />
					<xsd:enumeration value="navy" />
					<xsd:enumeration value="olive" />
					<xsd:enumeration value="orange" />
					<xsd:enumeration value="purple" />
					<xsd:enumeration value="red" />
					<xsd:enumeration value="silver" />
					<xsd:enumeration value="teal" />
					<xsd:enumeration value="white" />
					<xsd:enumeration value="yellow" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

	<!-- Define as operações CRUD que pode ser definidas em uma entidade -->
	<xsd:simpleType name="crudOperationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CREATE" />
			<xsd:enumeration value="RETRIEVE" />
			<xsd:enumeration value="UPDATE" />
			<xsd:enumeration value="DELETE" />
			<xsd:enumeration value="QUERY" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="crudOperationListType">
		<xsd:list itemType="local:crudOperationType" />
	</xsd:simpleType>

	<xsd:complexType name="PropertiesGroup">
		<xsd:sequence>
			<xsd:element name="property" type="local:PropertyType"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize este item
						para
						definir os metadados de uma propriedade da entidade
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
	</xsd:complexType>

	<xsd:complexType name="PropertyType" abstract="true">
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="displayFormat" type="xsd:string" />
		<xsd:attribute name="defaultValue" type="xsd:string" />
		<xsd:attribute name="editMask" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Definindo HTML para propriedades String, o sistema usará 
				editor de HTML para editar o campo.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="visible" type="xsd:boolean"
			default="false" />
		<xsd:attribute name="required" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="readOnly" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="calculated" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="valuesList" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir uma
					lista de
					valores separados por vírgula que poderão ser usados na
					tela de edição.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PropertyNumericType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="minimum" type="xsd:integer" />
				<xsd:attribute name="maximum" type="xsd:integer" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyStringType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyBooleanType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyCalendarType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyEntityType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="editShowEmbedded" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em 
							uma subseção para preenchimento in loco dos dados.
							É útil quando a entidade possui uma propriedade que é do tipo IEntity,
							mas que deve estar relacionada somente com esta entidade.
							Como se fosse um relacionamento OneToOne, mas somente em tela.
							Isto é valido para coleções também. Neste caso, os itens da coleção
							estarão ligados somente a entidade atual. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="editShowList" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em uma lista
							(ComboBox) ou se uma tela de pesquisa deverá ser aberta para a
							escolha do valor desta propriedade.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="allowSubQuery" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Durante uma
							pesquisa,
							o termo solicitado é
							procurado em todas propriedades de
							tipo primitivo da entidade atual. Esta
							opção, indica para que o
							termo também seja procurado nas propriedades
							primitivas deste
							relacionamento. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="overrideType" type="local:classNameType">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr"> Permite especificar o tipo de entidade
						que deve ser armazenado por esta propriedade. Este tipo, sobrescreverá o tipo
						encontrato na classe e é útil para utilizar uma classe mais especialista do que
						o tipo definido pela propriedade. No entanto, a classe aqui definida deverá
						ser filha da classe definda na propriedade para evitar possíveis CastClassException.
						Exemplo: Um objeto que possui atributo do tipo Pessoa, mas que, neste atributo, 
						somente PessoaFisica deve ser utilizado. Assim, nos metadados, especializamos o tipo.
						É útil, quando uma classe extende uma super classe, mas que na subClasse, deseja-se 
						restringir o tipo herdado.
						Exemplo: basic.entities.AdesaoContrato  
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="EntityType">
		<xsd:sequence>
			<xsd:element name="group" type="local:PropertiesGroup"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize um grupo para
						organizar propriedades da entidade que possuam algum
						relacionamento. Os grupos oferecem um recurso visual para
						montagem
						de telas de entidades que possuam muitas propriedades.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="className" type="local:classNameType"
			use="optional" />
		<xsd:attribute name="runQueryOnOpen" type="xsd:boolean"
			default="true">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir se
					quando a
					tela de pesquisa for invocada para a entidade atual, a
					pesquisa já
					deverá ser aberta com, pelo menos, uma página
					preenchida. É muito
					útil quando a entidade possui poucas instâncias
					e evitar que o
					operador digite algo para depois realizar a busca.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="crudOperations" type="local:crudOperationListType">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Define as operações
					CRUD que
					podem ser aplicadas à entidade.
					Esta restrição somente é
					aplicada às
					telas CRUD. A entidade poderá ser
					Criada, Obtida,
					Alterada e
					Excluida, mas somente
					por serviços CRUD e nunca por telas
					CRUD.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="propertiesInQueryGrid" type="xsd:IDREFS">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir a
					lista com o
					nome das propriedades que aparecerão na tela de grid. A
					ordem na
					lista é respeitada na geração da tela. Somente nomes de
					propriedades já declaradas são aceitas aqui.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:element name="entity" type="local:EntityType">
	</xsd:element>
</xsd:schema>

=== lgvalent/monstrengo/Basic/src/main/java/br/com/orionsoft/basic/entities/ContratoComAdesao.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="" label="Contrato com Adesões" name="ContratoComAdesao" propertiesInQueryGrid="id inativo categoria pessoa dataInicio dataVencimento dataRescisao observacoes representante contatos adesoes codigo" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.basic.entities.ContratoComAdesao" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyBooleanType" description="" hint="Define se o Contrato está ativo ou está marcado como inativo. O sistema não gerará cobrança para contratos inativos." label="Inativo" name="inativo" required="true" defaultValue="não"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica a categoria " label="Categoria" name="categoria" editShowList="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica a pessoa (empresa ou autônomo) à qual pertence este Contrato" label="Pessoa" name="pessoa" required="true" allowSubQuery="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica uma pessoa, vendedor ou representante comercial, que é responsável por este Contrato" label="Representante" name="representante" editShowList="true" required="true"/>
        <property xsi:type="PropertyStringType" description="Este código pode ser utilizado para diversos fins pelas especializações dos contratos" hint="Define um código para esse contrato" label="Código" name="codigo"/>
        <property xsi:type="PropertyStringType" description="" hint="Define em qual conta contábil serão registradas as movimentações deste item de custo" label="Código da conta contábil" name="codigoContaContabil"/>
    </group>
    <group description="" hint="" label="Datas e vencimentos" name="Vencimento">
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o Contrato entra em vigor" label="Data de início" name="dataInicio" required="true" defaultValue="nowDate()"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o Contrato foi rescindido" label="Data de rescisão" name="dataRescisao"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data a partir da qual este contrato não poderá ser mais utilizado pelo seu usuário (empresa ou autônomo)" label="Data de vencimento" name="dataVencimento"/>
    </group>
    <group description="" hint="" label="Controle de contatos realizados" name="Contato">
        <property xsi:type="PropertyEntityType" description="" hint="Indica os contatos que foram realizados e registrados" label="Contatos registrados" name="contatos"/>
    </group>
    <group description="" hint="" label="Adesões deste contrato" name="Adesoes">
        <property xsi:type="PropertyEntityType" description="" hint="" label="Adesões" name="adesoes" editShowEmbedded="true"/>
    </group>
    <group description="" hint="" label="Observações do contrato" name="Observações">
        <property xsi:type="PropertyEntityType" description="" hint="" label="Observações" name="observacoes" editShowEmbedded="true"/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/LancamentoItem.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="Um item de lançamento representa um 'produto' que está sendo cobrado ou recebido. Neste item é possivel observa quando ele foi gerado, sua data de competência, quem gerou o item e qual contrato será responsável pelo seu recebimento/pagamento" hint="" label="Lançamento Item" name="LancamentoItem" propertiesInQueryGrid="id dataLancamento dataCompetencia descricao contrato adesaoContrato valor peso centroCusto classificacaoContabil itemCusto lancamento" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.gerenciador.entities.LancamentoItem" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Dados gerais" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data em que este item foi gerado para o contrato" label="Data do lançamento" name="dataLancamento" required="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data de competência desta receita ou despesa" label="Data de competência" name="dataCompetencia" required="true"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Descrição" name="descricao"/>
    </group>
    <group description="" hint="" label="Detalhes" name="Detalhes">
        <property xsi:type="PropertyEntityType" description="" hint="" label="Centro de custo" name="centroCusto" required="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Item de custo" name="itemCusto" required="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Classificação Contábil" name="classificacaoContabil"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor" name="valor" required="true"/>
        <property xsi:type="PropertyNumericType" description="" hint="Indica o quanto o valor deste item representa no valor total do lançamento" label="Peso" name="peso" readOnly="true"/>
    </group>
    <group description="" hint="" label="Contratos" name="Contratos" colorName="blue">
        <property xsi:type="PropertyEntityType" description="Quando esta propriedade está vazia ela indica que o item ainda não foi lançado (faturado)" hint="Indica o lançamento do qual este item faz parte" label="Lançamento" name="lancamento" readOnly="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Define o contrato responsável pela receita/despesa" label="Contrato responsável" name="contrato" colorName="blue"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica quem foi que gerou esta receita/despesa" label="Adesão geradora" name="adesaoContrato" colorName="aqua"/>
    </group>
</entity>

=== lgvalent/monstrengo/Basic/src/br/com/orionsoft/basic/entities/endereco/Telefone.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="" label="Telefone" name="Telefone" propertiesInQueryGrid="id ddd numero ramal tipoTelefone telefoneOperadora pessoa" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.basic.entities.endereco.Telefone" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica o tipo do Telefone (se comercial, residencial, celular etc.)" label="Tipo" name="tipoTelefone" editShowList="true" required="true" defaultValue="1"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do DDD da região. Ex. 44, 41, 11, 21, ..." label="Ddd" name="ddd" defaultValue="44"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do telefone" label="Número" name="numero" required="true" editMask="*****-****"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do ramal, se houver" label="Ramal" name="ramal"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica a operadora do telefone. Este dado pode estar desatualizado de acordo com a lei de portabilidade" label="Operadora" name="telefoneOperadora" editShowList="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Define a pessoa associada ao telefone" label="Pessoa" name="pessoa" readOnly="true" allowSubQuery="true"/>
    </group>
</entity>

=== lgvalent/monstrengo/Financeiro/src/br/com/orionsoft/financeiro/documento/cobranca/DocumentoCobrancaCategoria.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" className="br.com.orionsoft.financeiro.documento.cobranca.DocumentoCobrancaCategoria" crudOperations="CREATE UPDATE RETRIEVE DELETE QUERY" propertiesInQueryGrid="id nome contaPadrao convenioCobranca layoutId" name="DocumentoCobrancaCategoria" label="DocumentoCobrancaCategoria" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group name="Geral" label="Dados gerais" hint="" description="">
        <property xsi:type="PropertyNumericType" name="id" label="Id"/>
        <property xsi:type="PropertyStringType" name="nome" label="Nome" hint="Define o nome da categoria do documento cobrança"/>
        <property xsi:type="PropertyEntityType" name="contaPadrao" label="Conta padrão" editShowList="true" hint="Define a conta padrão para lançamentos desta categoria de documento."/>
        <property xsi:type="PropertyEntityType" name="convenioCobranca" label="Convênio" editShowList="true" hint="Define o convênio que regula esta modelidade de cobrança"/>
        <property xsi:type="PropertyNumericType" name="layoutId" label="Layout de impressão" hint="Define o identificador do layout de impressão do documento de cobrança que o convênio deverá usar para esta categoria." description="Verifique quais são os valores aceitos pelo convênio desta categoria no cadastro do convênio."/>
    </group>
    <group name="Instrucoes" label="Formatação e mensangens de títulos" hint="" description="">
        <property xsi:type="PropertyStringType" name="formatoInstrucoes0" label="Formato da instrução 0" hint="Define o formato de montagem da instrução 0 que é calculada pelo sistema." description="Utilize os formatos:&lt;li&gt;%1$d para inserir os dias de atraso&lt;/li&gt;&lt;li&gt;%2$.2f%% para inserir o percentual da multa&lt;/li&gt;&lt;li&gt;%3$.2f%% para inserir o percentual dos juros&lt;/li&gt;Obs.: Alguns bancos não suportam mais que 80 caracteres em suas linhas de instruções. Obedeça este limite caso o documento seja impresso pelo banco via arquivo de remessa."/>
        <property xsi:type="PropertyStringType" name="instrucoes0" label="Instrução 0" calculated="true" hint="Define a primeira mensagem no campo Instruções a ser impressa no Boleto Bancário"/>
        <property xsi:type="PropertyStringType" name="instrucoes1" label="Instrução 1" hint="Define a segunda mensagem no campo Instruções a ser impressa no Boleto Bancário"/>
        <property xsi:type="PropertyStringType" name="instrucoes2" label="Instrução 2" hint="Define a terceira mensagem no campo Instruções a ser impressa no Boleto Bancário"/>
    </group>
    <group name="Juros" label="Juros, multas e outras cobranças" hint="" description="">
        <property xsi:type="PropertyNumericType" name="jurosMora" label="Juros/Mora por mês (%)" displayFormat="%,.2f%%" required="true" hint="Define o percentual dos juros para realizações dos cálculos sobre juros"/>
        <property xsi:type="PropertyNumericType" name="multaAtraso" label="Multa por atraso (%)" displayFormat="%,.2f%%" required="true" hint="Define o percentual da multa para realizações dos cálculos sobre multa por atraso"/>
        <property xsi:type="PropertyNumericType" name="descontoAntecipacao" label="Desconto por antecipação" hint="Define o total de desconto para documentos pagos com antecipaçã"/>
        <property xsi:type="PropertyNumericType" name="diasToleranciaMultaAtraso" label="Dias de tolerância do atraso" minimum="0" maximum="999" hint="Define quantos dias de atraso são tolerados antes da aplicação da multa e dos juros" description="Define quantos dias de atraso são tolerados antes da aplicação da multa e dos juros.&lt;br&gt;Se for maior que 0, é essencial adicionar esta informação na propriedade 'Formato da instrução 0'."/>
    </group>
    <group name="EMail" label="Configuração de envio de E-Mail" hint="" description="">
        <property xsi:type="PropertyEntityType" name="contaEMail" label="Conta de E-Mail" editShowList="true" hint="Esta conta de Email será utilizada para enviar os documentos de cobrança com o arquivo PDF"/>
        <property xsi:type="PropertyStringType" name="mensagemEMail" label="Mensagem do E-Mail" editMask="HTML" hint="Define a mensagem do E-Mail enviado com o Documento de Cobrança anexado" description="É possível usar tags HTML e também de CrudExpressions #{DocumentoCobranca[?].PROPRIEDADE}, onde PROPRIEDADE pode ser data, valor, contrato, convenioCobranca, documentoCobrancaCategoria."/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Monstrengo/src/br/com/orionsoft/monstrengo/mail/entities/EmailAccount.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="Permite configura cadastrar uma conta de e-mail que poderá ser usada nos serviços de envio de e-mail" hint="" label="Conta de e-mail" name="EmailAccount" propertiesInQueryGrid="id useAsDefault host user senderName senderMail" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.monstrengo.mail.entities.EmailAccount" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Dados da conta" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyStringType" description="mail.servername.com.br:portNumber" hint="Define o endereço do servidor SMTP que será utilizado para enviar os e-mails" label="Host" name="host"/>
        <property xsi:type="PropertyStringType" description="Preencha este campo apenas se a conexão com o servidor exigir autenticação." hint="Define o usuário que será utilizado para a autenticação no servidor" label="Nome do usuário" name="user"/>
        <property xsi:type="PropertyStringType" description="Preencha este campo apenas se a conexão com o servidor exigir autenticação." hint="Define a senha que será utilizado para autenticação no servidor" label="Senha do usuário" name="password"/>
        <property xsi:type="PropertyStringType" description="Define o nome do remetente que aparecerá nos e-mails enviados por esta conta" hint="Define o nome do remetente para esta conta" label="Nome do remetente" name="senderName"/>
        <property xsi:type="PropertyStringType" description="Define o e-mail do remetente que aparecerá nos e-mails enviados por esta conta" hint="Define o e-mail do remetente para esta conta" label="e-mail do remetente" name="senderMail"/>
    </group>
    <group description="" hint="" label="Configuração" name="Configuração">
        <property xsi:type="PropertyStringType" description="Ex.: mail.smtp.starttls.enable=true;mail.smtp.auth=true;" hint="Permite definir configurações adicionais exigidas por alguns serviços SMTP" label="Configurações adicionais" name="properties"/>
        <property xsi:type="PropertyBooleanType" description="Marcando esta propriedade, você definirá esta conta como a padrão para envio de e-mail. Outra conta padrão marcada será automaticamente desmarcada. A conta padrão é utilizada pelo serviço de envio de e-Mail quando nenhuma conta é especificada." hint="Define esta conta de e-mail como a conta padrão" label="Usar esta conta como padrão" name="useAsDefault"/>
    </group>
</entity>
