=== lgvalent/monstrengo/MonstrengoMetadata/entityMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://orionsoft.net.br/entityMetadata" xmlns:local="http://orionsoft.net.br/entityMetadata"
	elementFormDefault="qualified">
	<!-- Define um conjunto comum de metadados de textos aplicáveis a Entity, 
		Group e Property -->
	<xsd:attributeGroup name="commonMetadataAttributes">
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="label" type="xsd:string" default=""/>
		<xsd:attribute name="hint" type="xsd:string" default=""/>
		<xsd:attribute name="description" type="xsd:string" default=""/>
		<xsd:attribute name="colorName" type="local:colorNameType">
			<xsd:annotation><xsd:documentation> 
			Permite definir a cor pelo nome CSS ou pelo valor
			hexadecimal correspondente.
			</xsd:documentation></xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>

	<!-- Define o tipo que valida o nome de uma classe -->
	<xsd:simpleType name="classNameType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(([a-z]|[0-9])+.)*[A-Z][a-z]*([A-Z]|[a-z]|[0-9_])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Permite definir a cor pelo nome ou pelo código Hexadecimal -->
	<xsd:simpleType name="colorNameType">
		<xsd:union>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:annotation>
						<xsd:documentation>
							Fontes:http://www.kylirhorton.com/2008/a-regular-expression-that-matches-css-colors/
						</xsd:documentation>
					</xsd:annotation>
					<xsd:pattern
						value="(#[0-9a-fA-F]{3,6})|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" />
					<!-- xsd:pattern value="#([0-9A-Fa-f]{3,6})\b)|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" 
						/> -->
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="aqua" />
					<xsd:enumeration value="black" />
					<xsd:enumeration value="blue" />
					<xsd:enumeration value="fuchsia" />
					<xsd:enumeration value="gray" />
					<xsd:enumeration value="green" />
					<xsd:enumeration value="lime" />
					<xsd:enumeration value="maroon" />
					<xsd:enumeration value="navy" />
					<xsd:enumeration value="olive" />
					<xsd:enumeration value="orange" />
					<xsd:enumeration value="purple" />
					<xsd:enumeration value="red" />
					<xsd:enumeration value="silver" />
					<xsd:enumeration value="teal" />
					<xsd:enumeration value="white" />
					<xsd:enumeration value="yellow" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

	<!-- Define as operações CRUD que pode ser definidas em uma entidade -->
	<xsd:simpleType name="crudOperationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CREATE" />
			<xsd:enumeration value="RETRIEVE" />
			<xsd:enumeration value="UPDATE" />
			<xsd:enumeration value="DELETE" />
			<xsd:enumeration value="QUERY" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="crudOperationListType">
		<xsd:list itemType="local:crudOperationType" />
	</xsd:simpleType>

	<xsd:complexType name="PropertiesGroup">
		<xsd:sequence>
			<xsd:element name="property" type="local:PropertyType"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize este item
						para
						definir os metadados de uma propriedade da entidade
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
	</xsd:complexType>

	<xsd:complexType name="PropertyType" abstract="true">
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="displayFormat" type="xsd:string" />
		<xsd:attribute name="defaultValue" type="xsd:string" />
		<xsd:attribute name="editMask" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Definindo HTML para propriedades String, o sistema usará 
				editor de HTML para editar o campo.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="visible" type="xsd:boolean"
			default="false" />
		<xsd:attribute name="required" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="readOnly" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="calculated" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="valuesList" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir uma
					lista de
					valores separados por vírgula que poderão ser usados na
					tela de edição.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PropertyNumericType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="minimum" type="xsd:integer" />
				<xsd:attribute name="maximum" type="xsd:integer" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyStringType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyBooleanType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyCalendarType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyEntityType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="editShowEmbedded" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em 
							uma subseção para preenchimento in loco dos dados.
							É útil quando a entidade possui uma propriedade que é do tipo IEntity,
							mas que deve estar relacionada somente com esta entidade.
							Como se fosse um relacionamento OneToOne, mas somente em tela.
							Isto é valido para coleções também. Neste caso, os itens da coleção
							estarão ligados somente a entidade atual. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="editShowList" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em uma lista
							(ComboBox) ou se uma tela de pesquisa deverá ser aberta para a
							escolha do valor desta propriedade.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="allowSubQuery" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Durante uma
							pesquisa,
							o termo solicitado é
							procurado em todas propriedades de
							tipo primitivo da entidade atual. Esta
							opção, indica para que o
							termo também seja procurado nas propriedades
							primitivas deste
							relacionamento. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="overrideType" type="local:classNameType">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr"> Permite especificar o tipo de entidade
						que deve ser armazenado por esta propriedade. Este tipo, sobrescreverá o tipo
						encontrato na classe e é útil para utilizar uma classe mais especialista do que
						o tipo definido pela propriedade. No entanto, a classe aqui definida deverá
						ser filha da classe definda na propriedade para evitar possíveis CastClassException.
						Exemplo: Um objeto que possui atributo do tipo Pessoa, mas que, neste atributo, 
						somente PessoaFisica deve ser utilizado. Assim, nos metadados, especializamos o tipo.
						É útil, quando uma classe extende uma super classe, mas que na subClasse, deseja-se 
						restringir o tipo herdado.
						Exemplo: basic.entities.AdesaoContrato  
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="EntityType">
		<xsd:sequence>
			<xsd:element name="group" type="local:PropertiesGroup"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize um grupo para
						organizar propriedades da entidade que possuam algum
						relacionamento. Os grupos oferecem um recurso visual para
						montagem
						de telas de entidades que possuam muitas propriedades.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="className" type="local:classNameType"
			use="optional" />
		<xsd:attribute name="runQueryOnOpen" type="xsd:boolean"
			default="true">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir se
					quando a
					tela de pesquisa for invocada para a entidade atual, a
					pesquisa já
					deverá ser aberta com, pelo menos, uma página
					preenchida. É muito
					útil quando a entidade possui poucas instâncias
					e evitar que o
					operador digite algo para depois realizar a busca.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="crudOperations" type="local:crudOperationListType">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Define as operações
					CRUD que
					podem ser aplicadas à entidade.
					Esta restrição somente é
					aplicada às
					telas CRUD. A entidade poderá ser
					Criada, Obtida,
					Alterada e
					Excluida, mas somente
					por serviços CRUD e nunca por telas
					CRUD.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="propertiesInQueryGrid" type="xsd:IDREFS">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir a
					lista com o
					nome das propriedades que aparecerão na tela de grid. A
					ordem na
					lista é respeitada na geração da tela. Somente nomes de
					propriedades já declaradas são aceitas aqui.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:element name="entity" type="local:EntityType">
	</xsd:element>
</xsd:schema>

=== lgvalent/monstrengo/Financeiro/src/br/com/orionsoft/financeiro/documento/pagamento/dinheiro/DocumentoDinheiro.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="" label="Dinheiro" name="DocumentoDinheiro" propertiesInQueryGrid="id data dataVencimento valor contrato convenioPagamento dataCancelamento " crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.documento.pagamento.dinheiro.DocumentoDinheiro" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id" readOnly="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica o Contrato com a pessoa relacionada a este documento" label="Contrato" name="contrato" required="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica se o documento foi uma receita ou despesa (entrada ou saída)" label="Transação" name="transacao"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor" name="valor" required="true"/>
    </group>
    <group description="" hint="" label="Datas e vencimento" name="Datas">
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o documento foi criado" label="Data do documento" name="data"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que vence o documento" label="Data de vencimento" name="dataVencimento"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que foi realizada a última impressão deste documento" label="Data de impressão" name="dataImpressao"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data de cancelamento do documento" label="Data de cancelamento do documento" name="dataCancelamento"/>
    </group>
    <group description="" hint="" label="Controle" name="Controle">
        <property xsi:type="PropertyEntityType" description="" hint="Indica em qual categoria este documento de pagamento se enquadra de acordo com as configurações atuais" label="Categoria do Documento de Pagamento" name="documentoPagamentoCategoria"/>
        <property xsi:type="PropertyEntityType" description="" hint="Configurações de controle de emissão e recebimento deste documento" label="Convênio" name="convenioPagamento"/>
        <property xsi:type="PropertyNumericType" description="" hint="Identificador numérido do layout que é usado para imprimir este documento" label="Layout de impressão" name="layoutId"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Número do documento" name="numeroDocumento" visible="false"/>
    </group>
    <group description="" hint="" label="Lançamentos vinculados" name="Lancamentos">
        <property xsi:type="PropertyEntityType" description="" hint="Indica quais lançamentos estão usando este documento como documento de pagamento previsto" label="Lancamentos" name="lancamentos"/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/LancamentoParcela.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="" label="Parcela de lançamento" name="LancamentoParcela" propertiesInQueryGrid="numero dataLancamento dataVencimento valor documentoCobranca lancamentoMovimento lancamento id " crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.gerenciador.entities.LancamentoParcela" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Número" name="numero"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Data de Lançamento" name="dataLancamento"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Data de Vencimento" name="dataVencimento"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor" name="valor"/>
    </group>
    <group description="" hint="" label="Detalhes" name="Detalhes">
        <property xsi:type="PropertyEntityType" description="" hint="" label="Lançamento" name="lancamento"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Documento de Cobrança" name="documentoCobranca"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica se esta parcela está quitada ou não, ou seja, possui algum movimento" label="Movimento de quitação" name="lancamentoMovimento"/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/documento/pagamento/cheque/DocumentoCheque.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="Documento de pagamento Cheque" label="Cheque" name="DocumentoCheque" propertiesInQueryGrid="contrato convenioPagamento data dataCancelamento dataImpressao dataVencimento documentoPagamentoCategoria id lancamentos layoutId numeroDocumento transacao valor agencia banco contaCorrente contaCorrenteDigito" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.documento.pagamento.cheque.DocumentoCheque" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Dados do cheque" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Banco" name="banco" required="true" editShowList="true"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Agência" name="agencia" required="true"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Conta Corrente" name="contaCorrente" required="true"/>
        <property xsi:type="PropertyStringType" description="" hint="Dígito da conta corrente" label="Dígito CC" name="contaCorrenteDigito" required="true"/>
        <property xsi:type="PropertyStringType" description="Este número será redefinido pelo gerenciador de cheques durante a impressão de documentos com transação de saída (pagamento)." hint="" label="Número do cheque" name="numeroDocumento"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor" name="valor" required="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Transação" name="transacao" required="true"/>
        <property xsi:type="PropertyNumericType" description="Se nenhum documento será impresso, é utilizado o identificador 0. Para outros layouts, a documentação do gerenciador de documento responsável deverá ser consultada." hint="Indica o layout de impressão que será utilizado para imprimir o documento" label="Identificador do layout de impressão" name="layoutId" required="true"/>
    </group>

    <group description="" hint="" label="Datas e vencimentos" name="Datas">
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o cheque foi cadastrado no sistema" label="Data cadastro" name="data" required="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Data de vencimento" name="dataVencimento" required="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em o cheque foi impresso" label="Data de impressão" name="dataImpressao"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Data de cancelamento" name="dataCancelamento"/>
    </group>
    <group description="" hint="" label="Controle" name="Controle">
        <property xsi:type="PropertyEntityType" description="" hint="Indica o Contrato com a pessoa relacionada a este documento" label="Contrato" name="contrato" required="true" colorName="blue"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Categoria de documento de pagamento" name="documentoPagamentoCategoria" editShowList="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Controlador do cheque" name="convenioPagamento" required="true" editShowList="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica os lançamentos que estão relacionados com este cheque" label="Lançamentos" name="lancamentos" readOnly="true"/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/IRRFTabela.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="Esta entidade permite definir os valores e alíquotas do IRRF de acordo com uma vigência" hint="Tabela de Imposto de Renda Retido na Fonte" label="Tabela de IRRF" name="IRRFTabela" propertiesInQueryGrid="id inicioVigencia finalVigencia deducaoDependente deducaoAposentado valorMinimoRecolhimento aliquotas" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" runQueryOnOpen="true" className="br.com.orionsoft.financeiro.gerenciador.entities.IRRFTabela" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Início da vigência" name="inicioVigencia"/>
        <property xsi:type="PropertyCalendarType" description="" hint="" label="Final da vigência" name="finalVigencia"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Dedução por dependente" name="deducaoDependente"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Dedução de aposentado" name="deducaoAposentado"/>
        <property xsi:type="PropertyNumericType" description="" hint="Define um valor mínimo a partir do qual o recolhimento é efetivado." label="Valor mínimo do recolhimento" name="valorMinimoRecolhimento"/>
    </group>
    <group description="" hint="" label="Definições das alíquotas" name="Aliquota">
        <property xsi:type="PropertyEntityType" description="" hint="" label="Alíquotas" name="aliquotas" editShowEmbedded="true"/>
    </group>
</entity>

=== lgvalent/monstrengo/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/IRRFAliquota.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="" label="Tabela IRRF - Alíquota" name="IRRFAliquota" runQueryOnOpen="true" propertiesInQueryGrid="id valorInicial valorFinal aliquota valorDeducao tabela" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.gerenciador.entities.IRRFAliquota" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Geral" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor inicial" name="valorInicial" />
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor final" name="valorFinal"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Alíquota" name="aliquota"/>
        <property xsi:type="PropertyNumericType" description="" hint="" label="Valor da dedução" name="valorDeducao"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Tabela" name="tabela" readOnly="true"/>
    </group>
</entity>

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/Lancamento.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="Esta entidade controla todos os dados necessários para realização de cobrança ou pagamento para um determinado contrato." hint="Lançamento de crédito ou débito" label="Lançamento" name="Lancamento" propertiesInQueryGrid="id contaPrevista contrato valor saldo data dataVencimento descricao" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.gerenciador.entities.Lancamento" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Dados gerais" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica a atual situação do lançamento" label="Situação" name="lancamentoSituacao" readOnly="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica a conta em que este lançamento será quitado." label="Conta prevista" name="contaPrevista" colorName="maroon"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica o contrato para o qual pertence este lançamento" label="Contrato" name="contrato" colorName="blue"/>
        <property xsi:type="PropertyNumericType" description="" hint="Valor total do lançamento" label="Valor" name="valor" required="true" minimum="0" maximum="9999999"/>
        <property xsi:type="PropertyNumericType" description="" hint="Indica o quanto falta ser pago deste lançamento ainda, descontando as quitações parciais" label="Saldo em aberto" name="saldo" readOnly="true" />
        <property xsi:type="PropertyStringType" description="" hint="Descreve sobre o quê é este lançamento" label="Descrição" name="descricao"/>
        <property xsi:type="PropertyStringType" description="" hint="Utilizado para armazenar o código deste lançamento em outros sistemas para facilitar conciliações durante a fase de importação de dados entre sistemas" label="Codigo externo" name="codigoExterno" visible="false"/>
    </group>
    <group description="" hint="" label="Datas" name="Datas">
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data em que foi criado este lançamento" label="Data do lançamento" name="data" required="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data do vencimento do lançamento. A partir desta data, o recebimento será realizado com multa e juros." label="Data do vencimento" name="dataVencimento" required="true"/>
        <property xsi:type="PropertyBooleanType" description="Se está propriedade estiver marcada, um lançamento vencido não será mais indicado como pendente" hint="Permite definir um lançamento como não recebível após o seu vencimento" label="Não receber após o vencimento" name="naoReceberAposVencimento"/>
    </group>
    <group description="" hint="" label="Itens de Custos e movimentações do lançamento" name="Items">
        <property xsi:type="PropertyEntityType" description="" hint="Define o tipo de operação. Útil para classificar os lançamentos e obter saldos consolidados por operação" label="Operação" name="operacao" visible="false"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica os itens que fazem parte deste lançamento" label="Itens do lançamento" name="lancamentoItens" editShowEmbedded="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica as movimentações de quitação, cancelamento e estorno que já ocorreram com este lançamento" label="Movimentação do lançamento" name="lancamentoMovimentos" editShowEmbedded="true"/>
    </group>
    <group description="" hint="" label="Documentos de cobrança e de pagamento" name="Documentos">
        <property xsi:type="PropertyEntityType" description="" hint="Define o documento que é utilizado para realizar a cobrança deste lançamento (Boleto, promissória, convênios, etc)" label="Documento de cobrança" name="documentoCobranca"/>
        <property xsi:type="PropertyEntityType" description="Esta propriedade é útil para gerar um documento (ex. Cheque) para pagamento de um fornecedor antes da quitação do lançamento. Assim, quando o fornecedor vier buscar o seu pagamento o sistema já utilizará este documento gerado como o documento de pagamento do lançamento. Assim, é possível emitir o documento de pagamento antes do pagamento efetivo ocorrer." hint="Indica qual é o documento de pagamento que já está preparado e será sugerido para o pagamento deste lançamento" label="Documento de pagamento previsto" name="documentoPagamento"/>
    </group>
</entity>
