=== lgvalent/monstrengo/MonstrengoMetadata/entityMetadata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://orionsoft.net.br/entityMetadata" xmlns:local="http://orionsoft.net.br/entityMetadata"
	elementFormDefault="qualified">
	<!-- Define um conjunto comum de metadados de textos aplicáveis a Entity, 
		Group e Property -->
	<xsd:attributeGroup name="commonMetadataAttributes">
		<xsd:attribute name="name" type="xsd:ID" use="required" />
		<xsd:attribute name="label" type="xsd:string" default=""/>
		<xsd:attribute name="hint" type="xsd:string" default=""/>
		<xsd:attribute name="description" type="xsd:string" default=""/>
		<xsd:attribute name="colorName" type="local:colorNameType">
			<xsd:annotation><xsd:documentation> 
			Permite definir a cor pelo nome CSS ou pelo valor
			hexadecimal correspondente.
			</xsd:documentation></xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>

	<!-- Define o tipo que valida o nome de uma classe -->
	<xsd:simpleType name="classNameType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="(([a-z]|[0-9])+.)*[A-Z][a-z]*([A-Z]|[a-z]|[0-9_])*" />
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Permite definir a cor pelo nome ou pelo código Hexadecimal -->
	<xsd:simpleType name="colorNameType">
		<xsd:union>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:annotation>
						<xsd:documentation>
							Fontes:http://www.kylirhorton.com/2008/a-regular-expression-that-matches-css-colors/
						</xsd:documentation>
					</xsd:annotation>
					<xsd:pattern
						value="(#[0-9a-fA-F]{3,6})|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" />
					<!-- xsd:pattern value="#([0-9A-Fa-f]{3,6})\b)|(aqua)|(black)|(blue)|(fuchsia)|(gray)|(green)|(lime)|(maroon)|(navy)|(olive)|(orange)|(purple)|(red)|(silver)|(teal)|(white)|(yellow)" 
						/> -->
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="aqua" />
					<xsd:enumeration value="black" />
					<xsd:enumeration value="blue" />
					<xsd:enumeration value="fuchsia" />
					<xsd:enumeration value="gray" />
					<xsd:enumeration value="green" />
					<xsd:enumeration value="lime" />
					<xsd:enumeration value="maroon" />
					<xsd:enumeration value="navy" />
					<xsd:enumeration value="olive" />
					<xsd:enumeration value="orange" />
					<xsd:enumeration value="purple" />
					<xsd:enumeration value="red" />
					<xsd:enumeration value="silver" />
					<xsd:enumeration value="teal" />
					<xsd:enumeration value="white" />
					<xsd:enumeration value="yellow" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>

	<!-- Define as operações CRUD que pode ser definidas em uma entidade -->
	<xsd:simpleType name="crudOperationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CREATE" />
			<xsd:enumeration value="RETRIEVE" />
			<xsd:enumeration value="UPDATE" />
			<xsd:enumeration value="DELETE" />
			<xsd:enumeration value="QUERY" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="crudOperationListType">
		<xsd:list itemType="local:crudOperationType" />
	</xsd:simpleType>

	<xsd:complexType name="PropertiesGroup">
		<xsd:sequence>
			<xsd:element name="property" type="local:PropertyType"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize este item
						para
						definir os metadados de uma propriedade da entidade
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
	</xsd:complexType>

	<xsd:complexType name="PropertyType" abstract="true">
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="displayFormat" type="xsd:string" />
		<xsd:attribute name="defaultValue" type="xsd:string" />
		<xsd:attribute name="editMask" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Definindo HTML para propriedades String, o sistema usará 
				editor de HTML para editar o campo.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="visible" type="xsd:boolean"
			default="false" />
		<xsd:attribute name="required" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="readOnly" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="calculated" type="xsd:boolean"
			default="true" />
		<xsd:attribute name="valuesList" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir uma
					lista de
					valores separados por vírgula que poderão ser usados na
					tela de edição.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="PropertyNumericType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="minimum" type="xsd:integer" />
				<xsd:attribute name="maximum" type="xsd:integer" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyStringType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyBooleanType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyCalendarType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PropertyEntityType">
		<xsd:complexContent>
			<xsd:extension base="local:PropertyType">
				<xsd:attribute name="editShowEmbedded" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em 
							uma subseção para preenchimento in loco dos dados.
							É útil quando a entidade possui uma propriedade que é do tipo IEntity,
							mas que deve estar relacionada somente com esta entidade.
							Como se fosse um relacionamento OneToOne, mas somente em tela.
							Isto é valido para coleções também. Neste caso, os itens da coleção
							estarão ligados somente a entidade atual. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="editShowList" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Define se na tela de
							edição da entidade, esta propriedade será mostrada em uma lista
							(ComboBox) ou se uma tela de pesquisa deverá ser aberta para a
							escolha do valor desta propriedade.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="allowSubQuery" type="xsd:boolean"
					default="true">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr">Durante uma
							pesquisa,
							o termo solicitado é
							procurado em todas propriedades de
							tipo primitivo da entidade atual. Esta
							opção, indica para que o
							termo também seja procurado nas propriedades
							primitivas deste
							relacionamento. 
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="overrideType" type="local:classNameType">
					<xsd:annotation>
						<xsd:documentation xml:lang="ptBr"> Permite especificar o tipo de entidade
						que deve ser armazenado por esta propriedade. Este tipo, sobrescreverá o tipo
						encontrato na classe e é útil para utilizar uma classe mais especialista do que
						o tipo definido pela propriedade. No entanto, a classe aqui definida deverá
						ser filha da classe definda na propriedade para evitar possíveis CastClassException.
						Exemplo: Um objeto que possui atributo do tipo Pessoa, mas que, neste atributo, 
						somente PessoaFisica deve ser utilizado. Assim, nos metadados, especializamos o tipo.
						É útil, quando uma classe extende uma super classe, mas que na subClasse, deseja-se 
						restringir o tipo herdado.
						Exemplo: basic.entities.AdesaoContrato  
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="EntityType">
		<xsd:sequence>
			<xsd:element name="group" type="local:PropertiesGroup"
				maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="ptBr">Utilize um grupo para
						organizar propriedades da entidade que possuam algum
						relacionamento. Os grupos oferecem um recurso visual para
						montagem
						de telas de entidades que possuam muitas propriedades.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="local:commonMetadataAttributes" />
		<xsd:attribute name="className" type="local:classNameType"
			use="optional" />
		<xsd:attribute name="runQueryOnOpen" type="xsd:boolean"
			default="true">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir se
					quando a
					tela de pesquisa for invocada para a entidade atual, a
					pesquisa já
					deverá ser aberta com, pelo menos, uma página
					preenchida. É muito
					útil quando a entidade possui poucas instâncias
					e evitar que o
					operador digite algo para depois realizar a busca.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="crudOperations" type="local:crudOperationListType">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Define as operações
					CRUD que
					podem ser aplicadas à entidade.
					Esta restrição somente é
					aplicada às
					telas CRUD. A entidade poderá ser
					Criada, Obtida,
					Alterada e
					Excluida, mas somente
					por serviços CRUD e nunca por telas
					CRUD.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="propertiesInQueryGrid" type="xsd:IDREFS">
			<xsd:annotation>
				<xsd:documentation xml:lang="ptBr">Permite definir a
					lista com o
					nome das propriedades que aparecerão na tela de grid. A
					ordem na
					lista é respeitada na geração da tela. Somente nomes de
					propriedades já declaradas são aceitas aqui.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:element name="entity" type="local:EntityType">
	</xsd:element>
</xsd:schema>

=== lgvalent/monstrengo/trunk/Monstrengo/src/br/com/orionsoft/monstrengo/security/entities/ApplicationUser.info.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<entity
    xmlns="http://orionsoft.net.br/entityMetadata" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://orionsoft.net.br/entityMetadata /home/lucio/workspace/Framework/src/br/com/orionsoft/framework/crud/entity/metadata/xml/templates/entityMetadata.xsd"
	name="ApplicationUser"
	label="Operador do sistema"
	description="Ao cadastrar um novo operador será atribuida uma senha inicial igual ao login do operador. O operador poderá alterar sua senha pelo atalho 'Alterar Senha' na tela inicial."
	colorName="red" 
	crudOperations="CREATE RETRIEVE UPDATE DELETE"
	propertiesInQueryGrid="id inactive name login"
	runQueryOnOpen="true"
	>

	<group name="g0" label="Informações de Autenticação" colorName="green">
		<property xsi:type="PropertyNumericType" 
		    name="id" 
			label="id"
			readOnly="true"
			colorName="fuchsia" 
			/>

		<property xsi:type="PropertyStringType" 
			name="name"
			label="Nome Completo" 
			hint="Define o nome completo do operador" 
			description="Define o nome do operador que será exibido em algumas impressões e outras áreas do sistema" 
			colorName="#F00"
			required="true"
			/>

		<property xsi:type="PropertyStringType" 
			name="login"
			label="Login" 
			hint="Define o login do operador" 
			description="O login é um nome curto usado para junto com a senha para realizar a autenticação no sistema" 
			colorName="#F00"
			required="true"
			/>

		<property xsi:type="PropertyBooleanType" 
			name="inactive"
			label="Inativo" 
			hint="Define se operador atual está inativo" 
			description="Operadores inativos não poderão acessar o Sistema" 
			colorName="#0F0"
			/>

		<property xsi:type="PropertyStringType" 
			name="password"
			label="Senha" 
			hint="Define a senha do operador" 
			colorName="#00F"
			required="true"
			/>
	</group>
	<group name="g1" label="Informações de grupos de direitos do operador"  colorName="navy" >
		<property xsi:type="PropertyEntityType" 
		    name="securityGroups" 
			label="Grupos de segurança"
			hint="Indica os grupos de segurança que aos quais operador pertence" 
			colorName="green"
			required="true" 
			/>
			<!-- toString="Você é o #{entity.enderecoCorrespondencia.logradouro} na cidade #{entity.enderecoCorrespondencia.municipio.nome}"  -->
	</group>
</entity>
<!--

 <group id="1">Informações de grupos de direitos do operador</group>

 <propertyBoolean name="id"/>
 
 <propertyString name="id"/> 
 
 <propertyCalendar name="id"/> 


.label=Operador do sistema
.description=Ao cadastrar um novo operador será atribuida uma senha inicial igual ao login do operador. O operador poderá alterar sua senha pelo atalho "Alterar Senha" na tela inicial.
.canCreate=true
.canRetrieve=true
.canUpdate=true
.canDelete=true
.runQueryOnOpen=true

group.0.name=Informações de autenticação
group.1.name=Informações de grupos de direitos do operador

id.index=0
id.readOnly=true
id.group=0

name.index=1
name.label=Nome completo
name.hint=Define o nome completo do operador
name.description=Define o nome do operador que será exibido em algumas impressões e outras áreas do sistema
name.visible=true
name.required=true
name.readOnly=false
name.size=50
name.group=0

login.index=2
login.label=Login
login.hint=Define o login do Operador
login.visible=true
login.required=true
login.readOnly=false
login.size=20
login.group=0

inactive.index=3
inactive.label=Inativo
inactive.hint=Define se operador atual está inativo
inactive.description=Operadores inativos não poderão acessar o Sistema
inactive.visible=true
inactive.required=false
inactive.readOnly=false
inactive.group=0

password.index=4
password.label=Senha
password.hint=Define a senha do Operador
password.visible=false
password.required=true
password.readOnly=false
password.size=20
password.group=0

securityGroups.index=5
securityGroups.label=Grupos de segurança
securityGroups.hint=Indica os grupos de segurança que aos quais operador pertence
securityGroups.type=br.com.orionsoft.monstrengo.security.entities.SecurityGroup
securityGroups.isSet=true
securityGroups.required=true
securityGroups.readOnly=false
securityGroups.visible=true
securityGroups.group=1
-->

=== lgvalent/monstrengo/trunk/Financeiro/src/br/com/orionsoft/financeiro/gerenciador/entities/Conta.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="" hint="Conta para movimentação do financeiro" label="Conta" name="Conta" colorName="maroon" propertiesInQueryGrid="id inativo nome contaCategoria dataAbertura dataEncerramento dataFechamento saldoAbertura" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.financeiro.gerenciador.entities.Conta" runQueryOnOpen="true" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
    <group description="" hint="" label="Dados gerais" name="Geral">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id" readOnly="true"/>
        <property xsi:type="PropertyBooleanType" description="" hint="Define se esta conta não deve ser mais usada para as movimentações financeiras" label="Encerrada" name="inativo"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Nome" name="nome"/>
        <property xsi:type="PropertyEntityType" description="" hint="Permite agrupar as contas em categorias específicas para facilitar os relatórios sintéticos" label="Categoria da conta" name="contaCategoria" editShowList="true"/>
        <property xsi:type="PropertyNumericType" description="Esta informação é importante para exibição correta do saldo da conta nos extratos" hint="Indica o valor que a conta possuia no momento em que foi cadastrada aqui no sistema" label="Saldo de abertura" name="saldoAbertura"/>
    </group>
    <group description="" hint="" label="Datas" name="Datas">
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data em que esta conta foi aberta aqui no sistema" label="Data de abertura" name="dataAbertura"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Indica a data em que esta conta foi encerrada e não deve mais utilizada pelo sistema" label="Data de encerramento" name="dataEncerramento"/>
        <property xsi:type="PropertyCalendarType" description="Nenhum movimento poderá ser inserido nesta conta antes desta data" hint="Indica a data em que ocorreu a conciliação da movimentação desta conta" label="Data de fechamento" name="dataFechamento"/>
    </group>
    <group description="" hint="" label="Segurança" name="Segurança">
        <property xsi:type="PropertyEntityType" description="Esta propriedade permite definir os usuários que podem visualizar, inserir, alterar ou remover movimentações da conta atual." 
        										hint="Indica quais usuários podem visualizar e movimentar esta conta" label="Usuários da conta" name="applicationUsers"
        										colorName="red"/>
    </group>
    <group description="Para o controle contábil das receitas/despesas no sistema, destaca-se três momentos:&lt;br/>
    					&lt;li>Quando o lançamento é registrado no sistema ocorre a previsão de receita ou despesa. Também chamada de conhecimento.&lt;/li>
    					&lt;li>No momento em que este lançamento é quitado, ocorre a movimentação.&lt;/li>
    					&lt;li>Em um terceiro momento, a quitação da dívida é marcada como compensada&lt;/li>
    					Quitação de dívidas com dinheiro sofrem compensação automática.&lt;br/> 
    					Quitação de dívidas com cheques e outros documentos de pagamento, devem ser compensados manualmente pelo operador. 
    					" hint="" label="Contabilidade" name="Contabilidade">
        <property xsi:type="PropertyStringType" description="" hint="" label="Código da Conta contábil prevista" name="contaContabilPrevista"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Código da Conta contábil para movimento" name="contaContabilMovimento"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Código da Conta contábil para compensação" name="contaContabilCompensacao"/>
        <property xsi:type="PropertyBooleanType" description="Marque esta opção para contas que não necessitam de conferência posterior, seja ela por extrato ou por supervisor. As quitações realizadas nestas contas serão automaticamente marcadas como compensadas" hint="Define que as quitações efetuadas nesta conta serão compensadas automaticamente, na mesma data de quitação" label="Compensação automática" name="compensacaoAutomatica"/>
    </group>
</entity>

=== lgvalent/monstrengo/Basic/src/main/java/br/com/orionsoft/basic/entities/pessoa/Fisica.info.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<entity xmlns="http://orionsoft.net.br/entityMetadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" description="Use esse cadastro como uma agenda geral com os dados de todas as pessoas que se relacionam com a empresa." hint="Pessoa física que possui algum relacionamento com a empresa" label="Pessoa Física" name="Fisica" propertiesInQueryGrid="id nome dataCadastro dataInicial documento email telefones" crudOperations="CREATE RETRIEVE UPDATE DELETE QUERY" className="br.com.orionsoft.basic.entities.pessoa.Fisica" colorName="purple" xsi:schemaLocation="http://orionsoft.net.br/entityMetadata http://orionsoft.net.br/entityMetadata.xsd">
	<group label="Dados pessoais" name="Dados">
        <property xsi:type="PropertyNumericType" description="" hint="" label="Id" name="id" readOnly="true"/>
        <property xsi:type="PropertyStringType" description="" hint="Nome e sobrenome da pessoa física" label="Nome" name="nome" required="true"/>
        <property xsi:type="PropertyStringType" description="" hint="Apelido de tratamento da pessoa" label="Apelido" name="apelido" visible="false"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Sexo" name="sexo" valuesList="M,F" required="true"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Nome da mãe" name="nomeMae"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Nome do pai" name="nomePai"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Estado civil" name="estadoCivil" editShowList="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Profissão" name="profissao"/>
        <property xsi:type="PropertyEntityType" description="Município em que a pessoa nasceu" hint="Município em que a pessoa nasceu" label="Naturalidade" name="naturalidade"/>
        <property xsi:type="PropertyEntityType" description="País onde nasceu" hint="País onde nasceu" label="Nacionalidade" name="nacionalidade" editShowList="true"/>
        <property xsi:type="PropertyBooleanType" description="" hint="Define se a pessoa é canhota" label="Canhota" name="canhota" defaultValue="não" visible="false"/>
        <property xsi:type="PropertyEntityType" description="" hint="Necessidades especiais de uma pessoa" label="Necessidades especiais" name="necessidadesEspeciais" visible="false"/>
	</group>

	<group label="Datas" name="Datas">
        <property xsi:type="PropertyCalendarType" description="" hint="Define a data em que foi feito o cadastro" label="Data do cadastro" name="dataCadastro" required="true" defaultValue="nowDate()"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data de nascimento da Pessoa" label="Data de nascimento" name="dataInicial"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data de óbito da pessoa" label="Data de óbito" name="dataFinal"/>
	</group>

	<group label="Documentos" name="Documentos">
        <property xsi:type="PropertyStringType" description="" hint="Número do CPF" label="CPF" name="documento" required="true" editMask="###.###.###-##"/>
        <property xsi:type="PropertyEntityType" description="Caso a pessoa cadastrada não possua um CPF, poderá utilizar o CPF de um responsável. Para isto, o responsável deverá ser identificado pelo nome e grau de parentesco." hint="Indica que o CPF utilizado pertence a outra pessoa" label="Responsável do CPF" name="responsavelCpf" visible="false" calculated="false" readOnly="true" editShowEmbedded="true"/>
        <property xsi:type="PropertyBooleanType" description="" hint="" label="Usar CPF de um responsável" name="usaResponsavelCpf" visible="false"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do Cadastro Municipal de Contribuintes" label="CMC" name="cmc" editMask="###.###-#"/>
        <property xsi:type="PropertyStringType" description="Este código é definido pela Agência Nacional de Saúde a um pessoa que é enviada pelo SIB (Sistema de Informação de Beneficiário)" hint="Código de Controle Operacional definido pela ANS" label="CCO" name="cco" editMask="#.###.###.###-##" visible="false"/>
        <property xsi:type="PropertyStringType" description="" hint="Também conhecido como número de reservista" label="Documento militar: número" name="documentoMilitarNumero" visible="false"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Documento militar: órgão" name="documentoMilitarOrgao" valuesList="MEX,MMA,MAE"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="Documento militar: tipo" name="documentoMilitarTipo" editShowList="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o documento foi expedido pelo órgão" label="Documento militar: data de expedição" name="documentoMilitarDataExpedicao"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="RG: Número" name="rgNumero"/>
        <property xsi:type="PropertyStringType" description="SESP, SSP, IM" hint="Abreviação do orgão expedidor do RG" label="RG: Órgão expedidor" name="rgOrgaoExpedidor"/>
        <property xsi:type="PropertyEntityType" description="" hint="Unidade Federativa (Estado) expedidor do RG" label="RG: UF expedidor" name="rgUfExpedidor" editShowList="true"/>
        <property xsi:type="PropertyCalendarType" description="" hint="Data em que o documento RG foi expedido" label="RG: Data de expedição" name="rgDataExpedicao"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do PIS-PASEP" label="PIS/PASEP" name="pisPasep" editMask="###.#####.##-#"/>
        <property xsi:type="PropertyStringType" description="" hint="Número do cadastro INSS" label="INSS" name="inss" editMask="###.###.###-##"/>
	</group>

	<group label="Endereços para contato" name="Endereços">
        <property xsi:type="PropertyStringType" description="Cadastre vários e-mails, separando-os com ';'. O último e-mail da lista será usado para enviar a senha para o cadastro on-line." hint="Endereço eletrônico da Pessoa" label="E-Mail" name="email"/>
        <property xsi:type="PropertyStringType" description="" hint="Endereço da página pessoal na internet" label="Página na Internet" name="www"/>
        <property xsi:type="PropertyEntityType" description="" hint="Indica o endereço padrão que o sistema utiliza para envio de mala direta e documentos" label="Endereço principal" name="enderecoCorrespondencia" required="true" editShowEmbedded="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="Define outros endereços da pessoa" editShowEmbedded="true" label="Outros endereços" name="enderecos"/>
        <property xsi:type="PropertyEntityType" description="" hint="Lista com os números dos telefones para contato" label="Telefones" name="telefones" editShowEmbedded="true"/>
	</group>

	<group label="Informações sobre os contratos" name="Contratos">
        <property xsi:type="PropertyEntityType" description="" hint="Indica os contratos cadastrados para a Pessoa Física" label="Contratos" name="contratos" colorName="blue" readOnly="true"/>
	</group>

    <group description="" hint="" label="Responsável contábil" name="Contabil">
        <property xsi:type="PropertyEntityType" description="" hint="Escritório responsável pela contabilidade desta pessoa física" label="Escritorio contábil" name="escritorioContabil"/>
        <property xsi:type="PropertyEntityType" description="" hint="Contador responsável pela contabilidade desta pessoa física" label="Contador" name="contador" />
    </group>

	<group label="Dados sobre segurança" name="Segurança">
        <property xsi:type="PropertyEntityType" description="" hint="Informações sobre login e senha para a pessoa acessar o sistema" label="Usuário" name="applicationUser"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="Senha" name="senha"/>
        <property xsi:type="PropertyStringType" description="" hint="" label="CodigoSeguranca" name="codigoSeguranca"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="AsFisica" name="asFisica" visible="false" calculated="true" readOnly="true"/>
        <property xsi:type="PropertyEntityType" description="" hint="" label="AsJuridica" name="asJuridica" visible="false" calculated="true" readOnly="true"/>
        <property xsi:type="PropertyBooleanType" description="" hint="" label="Fisica" name="fisica" visible="false" calculated="true" readOnly="true"/>
        <property xsi:type="PropertyBooleanType" description="" hint="" label="Juridica" name="juridica" visible="false" calculated="true" readOnly="true"/>
	</group>
</entity>
